### ISSUE TITLE
error to load in console 

### ISSUE THREAD

**Issue by elDarksoul** [Rearth/Origen#3]
07:11:52 ERROR]: [com.dfsek.terra.registry.master.ConfigRegistry] Error loading config pack origen
com.dfsek.tectonic.api.exception.LoadException: Failed to load configuration:
        Configuration: pack.yml
        Message: No such entry: TRANSLATE
        Path: samplers.rawElevation...samplers.noise..
        Full Path: 
                From configuration "pack.yml"
                In entry "samplers"
                In entry "rawElevation"
                From configuration "math/samplers/terrain.yml"
                In entry "."
                With type "EXPRESSION"
                In entry "samplers"
                In entry "noise"
                In entry "."
        at com.dfsek.terra.config.loaders.GenericTemplateSupplierLoader.lambda$load$0(GenericTemplateSupplierLoader.java:49) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at com.dfsek.terra.config.loaders.GenericTemplateSupplierLoader.load(GenericTemplateSupplierLoader.java:49) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.getObject(ConfigLoader.java:210) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadType(ConfigLoader.java:204) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadValue(ConfigLoader.java:161) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.template.ReflectiveTemplateLoader.load(ReflectiveTemplateLoader.java:42) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.load(ConfigLoader.java:151) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:26) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.getObject(ConfigLoader.java:210) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadType(ConfigLoader.java:204) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.config.loaders.LinkedHashMapLoader.load(LinkedHashMapLoader.java:44) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.config.loaders.LinkedHashMapLoader.load(LinkedHashMapLoader.java:32) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.getObject(ConfigLoader.java:213) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadType(ConfigLoader.java:204) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadValue(ConfigLoader.java:161) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.template.ReflectiveTemplateLoader.load(ReflectiveTemplateLoader.java:42) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.load(ConfigLoader.java:151) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.config.loaders.GenericTemplateSupplierLoader.load(GenericTemplateSupplierLoader.java:48) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.getObject(ConfigLoader.java:210) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadType(ConfigLoader.java:204) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadValue(ConfigLoader.java:161) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.template.ReflectiveTemplateLoader.load(ReflectiveTemplateLoader.java:42) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.load(ConfigLoader.java:151) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.object.ObjectTemplateLoader.load(ObjectTemplateLoader.java:26) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.getObject(ConfigLoader.java:210) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadType(ConfigLoader.java:204) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:26) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.loaders.generic.HashMapLoader.load(HashMapLoader.java:14) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.getObject(ConfigLoader.java:213) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadType(ConfigLoader.java:204) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.loadValue(ConfigLoader.java:161) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.impl.loading.template.ReflectiveTemplateLoader.load(ReflectiveTemplateLoader.java:42) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.load(ConfigLoader.java:151) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.tectonic.api.loader.ConfigLoader.load(ConfigLoader.java:147) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.config.pack.ConfigPackImpl.lambda$new$2(ConfigPackImpl.java:175) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.api.event.events.config.pack.ConfigPackLoadEvent.loadTemplate(ConfigPackLoadEvent.java:36) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.addons.noise.NoiseAddon.lambda$initialize$18(NoiseAddon.java:139) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.lambda$handle$0(EventContextImpl.java:50) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.handle(EventContextImpl.java:50) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.lambda$handle$0(FunctionalEventHandlerImpl.java:52) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.handle(FunctionalEventHandlerImpl.java:48) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.event.EventManagerImpl.lambda$callEvent$0(EventManagerImpl.java:38) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at com.dfsek.terra.event.EventManagerImpl.callEvent(EventManagerImpl.java:38) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.config.pack.ConfigPackImpl.<init>(ConfigPackImpl.java:174) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.config.pack.ConfigPackImpl.<init>(ConfigPackImpl.java:125) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.load(ConfigRegistry.java:47) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.registry.master.ConfigRegistry.loadAll(ConfigRegistry.java:57) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.AbstractPlatform.lambda$load$0(AbstractPlatform.java:152) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.event.EventContextImpl.lambda$handle$0(EventContextImpl.java:50) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.EventContextImpl.handle(EventContextImpl.java:50) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.lambda$handle$0(FunctionalEventHandlerImpl.java:55) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at com.dfsek.terra.event.FunctionalEventHandlerImpl.handle(FunctionalEventHandlerImpl.java:48) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.event.EventManagerImpl.lambda$callEvent$0(EventManagerImpl.java:38) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
        at com.dfsek.terra.event.EventManagerImpl.callEvent(EventManagerImpl.java:38) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at com.dfsek.terra.bukkit.TerraBukkitPlugin.onEnable(TerraBukkitPlugin.java:59) ~[Terra-bukkit-6.3.1-BETA+73baaec6c-shaded.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

server version: 1.20.1

**Comment by Rearth** [comment]
Hi, it seems like you're using an older version of terra. As per the Readme, Origen requires terra 6.4 and up, while you're only using terra 6.3.1
